//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassList {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreConstStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreConstStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassList.CoreConstStrings", typeof(CoreConstStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured while communicating .
        /// </summary>
        internal static string ExCommunicationError {
            get {
                return ResourceManager.GetString("ExCommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwnload Error.
        /// </summary>
        internal static string ExDwAppHdr {
            get {
                return ResourceManager.GetString("ExDwAppHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while downloading application.
        /// </summary>
        internal static string ExDwApplInfo {
            get {
                return ResourceManager.GetString("ExDwApplInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMP file delete.
        /// </summary>
        internal static string ExDwBmpFolderDel {
            get {
                return ResourceManager.GetString("ExDwBmpFolderDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Screen specific information.
        /// </summary>
        internal static string ExDwPicFolderDel {
            get {
                return ResourceManager.GetString("ExDwPicFolderDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pzp file delete.
        /// </summary>
        internal static string ExDwPzpFolderDel {
            get {
                return ResourceManager.GetString("ExDwPzpFolderDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exporting alarm.
        /// </summary>
        internal static string ExExportAlarm {
            get {
                return ResourceManager.GetString("ExExportAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is being used by another process.
        /// </summary>
        internal static string ExFileIsUsedByAnotherProcessAlarmException {
            get {
                return ResourceManager.GetString("ExFileIsUsedByAnotherProcessAlarmException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string ExFileNotFound {
            get {
                return ResourceManager.GetString("ExFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Key Task Read.
        /// </summary>
        internal static string ExGlblKyHdr {
            get {
                return ResourceManager.GetString("ExGlblKyHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured in .
        /// </summary>
        internal static string ExGlobalError {
            get {
                return ResourceManager.GetString("ExGlobalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ExGlobalErrorHdr {
            get {
                return ResourceManager.GetString("ExGlobalErrorHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error ocurred while loading icon.
        /// </summary>
        internal static string ExIconLoadError {
            get {
                return ResourceManager.GetString("ExIconLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to importing alarm.
        /// </summary>
        internal static string ExImportAlarm {
            get {
                return ResourceManager.GetString("ExImportAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project ReadFile Error.
        /// </summary>
        internal static string ExRdBinApplicationHdr {
            get {
                return ResourceManager.GetString("ExRdBinApplicationHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred during Project Read operation.
        /// </summary>
        internal static string ExRdBinApplicationInfo {
            get {
                return ResourceManager.GetString("ExRdBinApplicationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during FTP Read operation.
        /// </summary>
        internal static string ExRdFTPInfo {
            get {
                return ResourceManager.GetString("ExRdFTPInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global keys Save Error.
        /// </summary>
        internal static string ExRdGlblKyHdr {
            get {
                return ResourceManager.GetString("ExRdGlblKyHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during Global Key Task Read operation.
        /// </summary>
        internal static string ExRdGlblKyInfo {
            get {
                return ResourceManager.GetString("ExRdGlblKyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Task Read.
        /// </summary>
        internal static string ExRdGlblTskHdr {
            get {
                return ResourceManager.GetString("ExRdGlblTskHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during Global Task Read operation.
        /// </summary>
        internal static string ExRdGlblTskInfo {
            get {
                return ResourceManager.GetString("ExRdGlblTskInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Read.
        /// </summary>
        internal static string ExRdLangHdr {
            get {
                return ResourceManager.GetString("ExRdLangHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during Language Read operation.
        /// </summary>
        internal static string ExRdLangInfo {
            get {
                return ResourceManager.GetString("ExRdLangInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during Data Logger Group Read operation.
        /// </summary>
        internal static string ExRdLoggerGrpInfo {
            get {
                return ResourceManager.GetString("ExRdLoggerGrpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Logger Read.
        /// </summary>
        internal static string ExRdLoggerHdr {
            get {
                return ResourceManager.GetString("ExRdLoggerHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during Data Logger Read operation.
        /// </summary>
        internal static string ExRdLoggerInfo {
            get {
                return ResourceManager.GetString("ExRdLoggerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Logger Information not found.
        /// </summary>
        internal static string ExRdLoggerNotFndInfo {
            get {
                return ResourceManager.GetString("ExRdLoggerNotFndInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modbus mapping Read.
        /// </summary>
        internal static string ExRdModbusHdr {
            get {
                return ResourceManager.GetString("ExRdModbusHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during Modbus mapping Read operation.
        /// </summary>
        internal static string ExRdModbusInfo {
            get {
                return ResourceManager.GetString("ExRdModbusInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Monitoring Read.
        /// </summary>
        internal static string ExRdMonitorHdr {
            get {
                return ResourceManager.GetString("ExRdMonitorHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during Data Monitoring Read operation.
        /// </summary>
        internal static string ExRdMonitorInfo {
            get {
                return ResourceManager.GetString("ExRdMonitorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during Node Broadcast Settings Read operation.
        /// </summary>
        internal static string ExRdNodeBroadInfo {
            get {
                return ResourceManager.GetString("ExRdNodeBroadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during G9SP Node Settings Read operation.
        /// </summary>
        internal static string ExRdNodeG9SPInfo {
            get {
                return ResourceManager.GetString("ExRdNodeG9SPInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Node Read.
        /// </summary>
        internal static string ExRdNodeHdr {
            get {
                return ResourceManager.GetString("ExRdNodeHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during Node Read operation.
        /// </summary>
        internal static string ExRdNodeInfo {
            get {
                return ResourceManager.GetString("ExRdNodeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Node Information not found.
        /// </summary>
        internal static string ExRdNodeInfoNotFound {
            get {
                return ResourceManager.GetString("ExRdNodeInfoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during Node MIT Settings Read operation.
        /// </summary>
        internal static string ExRdNodeMITInfo {
            get {
                return ResourceManager.GetString("ExRdNodeMITInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during Siemens USS Node Settings Read operation.
        /// </summary>
        internal static string ExRdNodeUSSInfo {
            get {
                return ResourceManager.GetString("ExRdNodeUSSInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Downloadable Information Read.
        /// </summary>
        internal static string ExRdNonDwnHdr {
            get {
                return ResourceManager.GetString("ExRdNonDwnHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during Non Downloadable Read operation.
        /// </summary>
        internal static string ExRdNonDwnInfo {
            get {
                return ResourceManager.GetString("ExRdNonDwnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power On Task Read.
        /// </summary>
        internal static string ExRdPowerOnHdr {
            get {
                return ResourceManager.GetString("ExRdPowerOnHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during Power On Task Read operation.
        /// </summary>
        internal static string ExRdPowerOninfo {
            get {
                return ResourceManager.GetString("ExRdPowerOninfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during Data Logger Printing Read operation.
        /// </summary>
        internal static string ExRdPrntLoggerInfo {
            get {
                return ResourceManager.GetString("ExRdPrntLoggerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Read Error.
        /// </summary>
        internal static string ExRdProjHdr {
            get {
                return ResourceManager.GetString("ExRdProjHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during Project Header Read operation.
        /// </summary>
        internal static string ExRdProjHdrInfo {
            get {
                return ResourceManager.GetString("ExRdProjHdrInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while reading Project Header.
        /// </summary>
        internal static string ExRdProjHdrXML {
            get {
                return ResourceManager.GetString("ExRdProjHdrXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during HW Info Read operation.
        /// </summary>
        internal static string ExRdProjHWInfo {
            get {
                return ResourceManager.GetString("ExRdProjHWInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Header HW information not found.
        /// </summary>
        internal static string ExRdProjHWNotFndInfo {
            get {
                return ResourceManager.GetString("ExRdProjHWNotFndInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during Project Variable Header Read operation.
        /// </summary>
        internal static string ExRdProjVarInfo {
            get {
                return ResourceManager.GetString("ExRdProjVarInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Variable Header not found.
        /// </summary>
        internal static string ExRdProjVarNotFndInfo {
            get {
                return ResourceManager.GetString("ExRdProjVarNotFndInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred during Project Read operation.
        /// </summary>
        internal static string ExRdProjXML {
            get {
                return ResourceManager.GetString("ExRdProjXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during Screen Saver Settings Read operation.
        /// </summary>
        internal static string ExRdScrnSaverInfo {
            get {
                return ResourceManager.GetString("ExRdScrnSaverInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Saver Settings not found.Default settings are assigned..
        /// </summary>
        internal static string ExRdScrnSvrInfoNotFnd {
            get {
                return ResourceManager.GetString("ExRdScrnSvrInfoNotFnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during Data Logger SETags Read operation.
        /// </summary>
        internal static string ExRdSETag {
            get {
                return ResourceManager.GetString("ExRdSETag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Parameters Read.
        /// </summary>
        internal static string ExRdSysParHdr {
            get {
                return ResourceManager.GetString("ExRdSysParHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during System Parameters Read operation.
        /// </summary>
        internal static string ExRdSysParInfo {
            get {
                return ResourceManager.GetString("ExRdSysParInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Tag Database found corrupted.
        /// </summary>
        internal static string ExRdTagCorruptInfo {
            get {
                return ResourceManager.GetString("ExRdTagCorruptInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Tag Group information not found.
        /// </summary>
        internal static string ExRdTagGrpBlankInfo {
            get {
                return ResourceManager.GetString("ExRdTagGrpBlankInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Tag Group information found corrupted.
        /// </summary>
        internal static string ExRdTagGrpCorruptInfo {
            get {
                return ResourceManager.GetString("ExRdTagGrpCorruptInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Group Read Error.
        /// </summary>
        internal static string ExRdTagGrpHdr {
            get {
                return ResourceManager.GetString("ExRdTagGrpHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Tag Database Read Error.
        /// </summary>
        internal static string ExRdTagHdr {
            get {
                return ResourceManager.GetString("ExRdTagHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during Project Tag Database Read operation.
        /// </summary>
        internal static string ExRdTagInfo {
            get {
                return ResourceManager.GetString("ExRdTagInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Tag Database not found.
        /// </summary>
        internal static string ExRdTagNotFndInfo {
            get {
                return ResourceManager.GetString("ExRdTagNotFndInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD Read.
        /// </summary>
        internal static string ExRdUSDHdr {
            get {
                return ResourceManager.GetString("ExRdUSDHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during Universal Serial Driver Read operation.
        /// </summary>
        internal static string ExRdUSDInfo {
            get {
                return ResourceManager.GetString("ExRdUSDInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use As Default Read.
        /// </summary>
        internal static string ExRdUseAsDefaultHdr {
            get {
                return ResourceManager.GetString("ExRdUseAsDefaultHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during Use As Default Read operation.
        /// </summary>
        internal static string ExRdUseAsDefaultInfo {
            get {
                return ResourceManager.GetString("ExRdUseAsDefaultInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Screen Read.
        /// </summary>
        internal static string ExRdWebScrnHdr {
            get {
                return ResourceManager.GetString("ExRdWebScrnHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during Web Screen Read operation.
        /// </summary>
        internal static string ExRdWebScrnInfo {
            get {
                return ResourceManager.GetString("ExRdWebScrnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Read.
        /// </summary>
        internal static string ExstrAlarmHdr {
            get {
                return ResourceManager.GetString("ExstrAlarmHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during Alarm Read operation.
        /// </summary>
        internal static string ExstrAlarmReadInfo {
            get {
                return ResourceManager.GetString("ExstrAlarmReadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Save Error.
        /// </summary>
        internal static string ExstrAlrmHdr {
            get {
                return ResourceManager.GetString("ExstrAlrmHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Monitor Error.
        /// </summary>
        internal static string ExstrDMonitorHdr {
            get {
                return ResourceManager.GetString("ExstrDMonitorHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during Ethernet Settings Read operation.
        /// </summary>
        internal static string ExstrEthernetReadInfo {
            get {
                return ResourceManager.GetString("ExstrEthernetReadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Header Ev3 Read.
        /// </summary>
        internal static string ExstrEV3ReadHdr {
            get {
                return ResourceManager.GetString("ExstrEV3ReadHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during Ev3 Read operation.
        /// </summary>
        internal static string ExstrEV3ReadInfo {
            get {
                return ResourceManager.GetString("ExstrEV3ReadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expansion Info Save Error.
        /// </summary>
        internal static string ExstrExpnHdr {
            get {
                return ResourceManager.GetString("ExstrExpnHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expansion Info Read.
        /// </summary>
        internal static string ExstrExpnReadHdr {
            get {
                return ResourceManager.GetString("ExstrExpnReadHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during Expansion Read operation.
        /// </summary>
        internal static string ExstrExpnReadInfo {
            get {
                return ResourceManager.GetString("ExstrExpnReadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Task Save Error.
        /// </summary>
        internal static string ExstrGlobalHdr {
            get {
                return ResourceManager.GetString("ExstrGlobalHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Header Read.
        /// </summary>
        internal static string ExstrProjHdr {
            get {
                return ResourceManager.GetString("ExstrProjHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured for Global Keys information.
        /// </summary>
        internal static string ExstrWrGlblKyInfo {
            get {
                return ResourceManager.GetString("ExstrWrGlblKyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured for Global Task information.
        /// </summary>
        internal static string ExstrWrGlblTskInfo {
            get {
                return ResourceManager.GetString("ExstrWrGlblTskInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured for Alarm information.
        /// </summary>
        internal static string ExstrWriteAlrmInfo {
            get {
                return ResourceManager.GetString("ExstrWriteAlrmInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured for Data Monitoring information.
        /// </summary>
        internal static string ExstrWriteDMonitorInfo {
            get {
                return ResourceManager.GetString("ExstrWriteDMonitorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured for Expansion Information.
        /// </summary>
        internal static string ExstrWriteExpnInfo {
            get {
                return ResourceManager.GetString("ExstrWriteExpnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Info Save Error.
        /// </summary>
        internal static string ExWrLangHdr {
            get {
                return ResourceManager.GetString("ExWrLangHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured for Language Information.
        /// </summary>
        internal static string ExWrLangInfo {
            get {
                return ResourceManager.GetString("ExWrLangInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datalogger Write Error.
        /// </summary>
        internal static string ExWrLoggerHdr {
            get {
                return ResourceManager.GetString("ExWrLoggerHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured for datalogger information.
        /// </summary>
        internal static string ExWrLoggerInfo {
            get {
                return ResourceManager.GetString("ExWrLoggerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modbus Slave Save Error.
        /// </summary>
        internal static string ExWrModbusHdr {
            get {
                return ResourceManager.GetString("ExWrModbusHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured for Modbus Slave Information.
        /// </summary>
        internal static string ExWrModbusInfo {
            get {
                return ResourceManager.GetString("ExWrModbusInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Node Write.
        /// </summary>
        internal static string ExWrNodeHdr {
            get {
                return ResourceManager.GetString("ExWrNodeHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured for Information of Node .
        /// </summary>
        internal static string ExWrNodeInfo {
            get {
                return ResourceManager.GetString("ExWrNodeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non downloadable information Save Error.
        /// </summary>
        internal static string ExWrNonDwnlHdr {
            get {
                return ResourceManager.GetString("ExWrNonDwnlHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured for Non downloadable information.
        /// </summary>
        internal static string ExWrNonDwnlInfo {
            get {
                return ResourceManager.GetString("ExWrNonDwnlInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power On Task Save Error.
        /// </summary>
        internal static string ExWrPowerHdr {
            get {
                return ResourceManager.GetString("ExWrPowerHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured for Power On task information.
        /// </summary>
        internal static string ExWrPowerOnInfo {
            get {
                return ResourceManager.GetString("ExWrPowerOnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured for datalogger Printing information.
        /// </summary>
        internal static string ExWrPrntLoggerInfo {
            get {
                return ResourceManager.GetString("ExWrPrntLoggerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred while saving project.
        /// </summary>
        internal static string ExWrProjXML {
            get {
                return ResourceManager.GetString("ExWrProjXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Header Information Save Error.
        /// </summary>
        internal static string ExWrProjXMLHdr {
            get {
                return ResourceManager.GetString("ExWrProjXMLHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred while saving project header information.
        /// </summary>
        internal static string ExWrProjXMLInfo {
            get {
                return ResourceManager.GetString("ExWrProjXMLInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Task Save Error (AH).
        /// </summary>
        internal static string ExWrScrnAHTskHdr {
            get {
                return ResourceManager.GetString("ExWrScrnAHTskHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Task Save Error (BS).
        /// </summary>
        internal static string ExWrScrnBSTskHdr {
            get {
                return ResourceManager.GetString("ExWrScrnBSTskHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Screen specific information.
        /// </summary>
        internal static string ExWrScrnInfo {
            get {
                return ResourceManager.GetString("ExWrScrnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Keys Task Save Error.
        /// </summary>
        internal static string ExWrScrnKyTskHdr {
            get {
                return ResourceManager.GetString("ExWrScrnKyTskHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Save Error for Group.
        /// </summary>
        internal static string ExWrScrnObjGrpHdr {
            get {
                return ResourceManager.GetString("ExWrScrnObjGrpHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Save Error for object task (Group).
        /// </summary>
        internal static string ExWrScrnObjGrpTskHdr {
            get {
                return ResourceManager.GetString("ExWrScrnObjGrpTskHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Save Error for object task.
        /// </summary>
        internal static string ExWrScrnObjTskHdr {
            get {
                return ResourceManager.GetString("ExWrScrnObjTskHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Save Error.
        /// </summary>
        internal static string ExWrScrnSaveHdr {
            get {
                return ResourceManager.GetString("ExWrScrnSaveHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured for Save Screen Info.
        /// </summary>
        internal static string ExWrScrnSaveInfo {
            get {
                return ResourceManager.GetString("ExWrScrnSaveInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Task Save Error (WS).
        /// </summary>
        internal static string ExWrScrnWSTskHdr {
            get {
                return ResourceManager.GetString("ExWrScrnWSTskHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured for datalogger Start End Time Tags.
        /// </summary>
        internal static string ExWrSELoggerInfo {
            get {
                return ResourceManager.GetString("ExWrSELoggerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Group Information Save Error.
        /// </summary>
        internal static string ExWrTagGrpHdr {
            get {
                return ResourceManager.GetString("ExWrTagGrpHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured for Tag Group Information.
        /// </summary>
        internal static string ExWrTagGrpInfo {
            get {
                return ResourceManager.GetString("ExWrTagGrpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Save Error.
        /// </summary>
        internal static string ExWrTagHdr {
            get {
                return ResourceManager.GetString("ExWrTagHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured for Tag Information.
        /// </summary>
        internal static string ExWrTagInfo {
            get {
                return ResourceManager.GetString("ExWrTagInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Univarsal serial driver Save Error.
        /// </summary>
        internal static string ExWrUSDHdr {
            get {
                return ResourceManager.GetString("ExWrUSDHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured for USS driver Information.
        /// </summary>
        internal static string ExWrUSDInfo {
            get {
                return ResourceManager.GetString("ExWrUSDInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use As Default Save Error.
        /// </summary>
        internal static string ExWrUseAsDefaultHdr {
            get {
                return ResourceManager.GetString("ExWrUseAsDefaultHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured for Use As Default Information.
        /// </summary>
        internal static string ExWrUseAsDefaultInfo {
            get {
                return ResourceManager.GetString("ExWrUseAsDefaultInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Screen Info Save Error.
        /// </summary>
        internal static string ExWrWebScrnHdr {
            get {
                return ResourceManager.GetString("ExWrWebScrnHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured for Web Screen Information.
        /// </summary>
        internal static string ExWrWebScrnInfo {
            get {
                return ResourceManager.GetString("ExWrWebScrnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Constant Value to a Tag.
        /// </summary>
        internal static string strAddAConstantValueToATag {
            get {
                return ResourceManager.GetString("strAddAConstantValueToATag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tag B to Tag A.
        /// </summary>
        internal static string strAddTagBToTagA {
            get {
                return ResourceManager.GetString("strAddTagBToTagA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APN.
        /// </summary>
        internal static string strAPN {
            get {
                return ResourceManager.GetString("strAPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Log Memory.
        /// </summary>
        internal static string strClearLogMemory {
            get {
                return ResourceManager.GetString("strClearLogMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Com1.
        /// </summary>
        internal static string strCom1 {
            get {
                return ResourceManager.GetString("strCom1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Com2.
        /// </summary>
        internal static string strCom2 {
            get {
                return ResourceManager.GetString("strCom2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Status.
        /// </summary>
        internal static string strCommSt {
            get {
                return ResourceManager.GetString("strCommSt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy HMI/PLC Block to HMI Block.
        /// </summary>
        internal static string strCopyPLCToPrizm {
            get {
                return ResourceManager.GetString("strCopyPLCToPrizm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy HMI Block to HMI/PLC Block.
        /// </summary>
        internal static string strCopyPrizmBlockToPrizmOrPLCBlock {
            get {
                return ResourceManager.GetString("strCopyPrizmBlockToPrizmOrPLCBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy RTC To PLC Block.
        /// </summary>
        internal static string strCopyRTCToPLC {
            get {
                return ResourceManager.GetString("strCopyRTCToPLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Tag B to Tag A.
        /// </summary>
        internal static string strCopyTagBToTagA {
            get {
                return ResourceManager.GetString("strCopyTagBToTagA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Tag to LED.
        /// </summary>
        internal static string strCopyTagToLED {
            get {
                return ResourceManager.GetString("strCopyTagToLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Screen From Tag.
        /// </summary>
        internal static string strCopyTagToSTR {
            get {
                return ResourceManager.GetString("strCopyTagToSTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        internal static string strDelay {
            get {
                return ResourceManager.GetString("strDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Media.
        /// </summary>
        internal static string strDestMedia {
            get {
                return ResourceManager.GetString("strDestMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Path.
        /// </summary>
        internal static string strDestPath {
            get {
                return ResourceManager.GetString("strDestPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP Enable Bit.
        /// </summary>
        internal static string strEnbl {
            get {
                return ResourceManager.GetString("strEnbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during import for after hiding tasks for screen number: .
        /// </summary>
        internal static string strErrorAH {
            get {
                return ResourceManager.GetString("strErrorAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during import for before showing tasks for screen number: .
        /// </summary>
        internal static string strErrorBSH {
            get {
                return ResourceManager.GetString("strErrorBSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination project has no PLC tags defined, hence can not import Copy HMI/PLC TO HMI, Copy RTC to PLC tasks from source project..
        /// </summary>
        internal static string strErrorImportCopyBlockTasks {
            get {
                return ResourceManager.GetString("strErrorImportCopyBlockTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in importing Global tasks..
        /// </summary>
        internal static string strErrorImportGTasks {
            get {
                return ResourceManager.GetString("strErrorImportGTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in importing Power On tasks..
        /// </summary>
        internal static string strErrorImportPTasks {
            get {
                return ResourceManager.GetString("strErrorImportPTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in importing screen after hiding tasks..
        /// </summary>
        internal static string strErrorImportScreenAHTasks {
            get {
                return ResourceManager.GetString("strErrorImportScreenAHTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in importing screen before showing tasks..
        /// </summary>
        internal static string strErrorImportScreenBSHTasks {
            get {
                return ResourceManager.GetString("strErrorImportScreenBSHTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in importing screen while showing tasks..
        /// </summary>
        internal static string strErrorImportScreenWSHTasks {
            get {
                return ResourceManager.GetString("strErrorImportScreenWSHTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during import for while showing tasks for screen number: .
        /// </summary>
        internal static string strErrorWSH {
            get {
                return ResourceManager.GetString("strErrorWSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during saving of Gateway block information.
        /// </summary>
        internal static string strErrWrite1 {
            get {
                return ResourceManager.GetString("strErrWrite1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GWY Error.
        /// </summary>
        internal static string strErrWrite2 {
            get {
                return ResourceManager.GetString("strErrWrite2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during reading of Gateway block information.
        /// </summary>
        internal static string strErrWrite3 {
            get {
                return ResourceManager.GetString("strErrWrite3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during saving of Gateway Error bit information.
        /// </summary>
        internal static string strErrWrite4 {
            get {
                return ResourceManager.GetString("strErrWrite4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during reading of Gateway Error Bit information.
        /// </summary>
        internal static string strErrWrite5 {
            get {
                return ResourceManager.GetString("strErrWrite5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during saving of Gateway Control Word information.
        /// </summary>
        internal static string strErrWrite6 {
            get {
                return ResourceManager.GetString("strErrWrite6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during reading of Gateway Control Word information.
        /// </summary>
        internal static string strErrWrite7 {
            get {
                return ResourceManager.GetString("strErrWrite7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethernet.
        /// </summary>
        internal static string strEthernet {
            get {
                return ResourceManager.GetString("strEthernet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute PLC Logic Block.
        /// </summary>
        internal static string strExecutePLCLogicBlock {
            get {
                return ResourceManager.GetString("strExecutePLCLogicBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Send Status.
        /// </summary>
        internal static string strFlSndSt {
            get {
                return ResourceManager.GetString("strFlSndSt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP Status.
        /// </summary>
        internal static string strFTPSt {
            get {
                return ResourceManager.GetString("strFTPSt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto Popup Screen.
        /// </summary>
        internal static string strGoToPopUpScreen {
            get {
                return ResourceManager.GetString("strGoToPopUpScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto Screen.
        /// </summary>
        internal static string strGotoScreen {
            get {
                return ResourceManager.GetString("strGotoScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Number.
        /// </summary>
        internal static string strGrpNmbr {
            get {
                return ResourceManager.GetString("strGrpNmbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Tasks.
        /// </summary>
        internal static string strImportTasks {
            get {
                return ResourceManager.GetString("strImportTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key&apos;s Specific Task.
        /// </summary>
        internal static string strKeysSpecificTask {
            get {
                return ResourceManager.GetString("strKeysSpecificTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Status.
        /// </summary>
        internal static string strMediaSt {
            get {
                return ResourceManager.GetString("strMediaSt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Connection Status.
        /// </summary>
        internal static string strNetConnSt {
            get {
                return ResourceManager.GetString("strNetConnSt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Screen.
        /// </summary>
        internal static string strNextScreen {
            get {
                return ResourceManager.GetString("strNextScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Com1_Node.
        /// </summary>
        internal static string strNodeCom1 {
            get {
                return ResourceManager.GetString("strNodeCom1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Com2_Node.
        /// </summary>
        internal static string strNodeCom2 {
            get {
                return ResourceManager.GetString("strNodeCom2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ethernet_Node.
        /// </summary>
        internal static string strNodeEthernet {
            get {
                return ResourceManager.GetString("strNodeEthernet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Screen.
        /// </summary>
        internal static string strPreviousScreen {
            get {
                return ResourceManager.GetString("strPreviousScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Data.
        /// </summary>
        internal static string strPrintData {
            get {
                return ResourceManager.GetString("strPrintData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string strPwd {
            get {
                return ResourceManager.GetString("strPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Trend Window.
        /// </summary>
        internal static string strRefreshTrendWindow {
            get {
                return ResourceManager.GetString("strRefreshTrendWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Resend Bit.
        /// </summary>
        internal static string strRsnd {
            get {
                return ResourceManager.GetString("strRsnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD Card Upload.
        /// </summary>
        internal static string strSDCardUpload {
            get {
                return ResourceManager.GetString("strSDCardUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send File At Every.
        /// </summary>
        internal static string strSendFileAtEvery {
            get {
                return ResourceManager.GetString("strSendFileAtEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set RTC.
        /// </summary>
        internal static string strSetRTC {
            get {
                return ResourceManager.GetString("strSetRTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Ethernet Configuration Screen.
        /// </summary>
        internal static string strShowEthernetConfigurationScreen {
            get {
                return ResourceManager.GetString("strShowEthernetConfigurationScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Media.
        /// </summary>
        internal static string strSrcMedia {
            get {
                return ResourceManager.GetString("strSrcMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Address.
        /// </summary>
        internal static string strSrvAddr {
            get {
                return ResourceManager.GetString("strSrvAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start External Logger.
        /// </summary>
        internal static string strStartExternalLogger {
            get {
                return ResourceManager.GetString("strStartExternalLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start External Logger Of Group No.
        /// </summary>
        internal static string strStartExternalLoggerOfGroupNo {
            get {
                return ResourceManager.GetString("strStartExternalLoggerOfGroupNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Logger.
        /// </summary>
        internal static string strStartLogger {
            get {
                return ResourceManager.GetString("strStartLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Logger Of Group No.
        /// </summary>
        internal static string strStartLoggerOfGroupNo {
            get {
                return ResourceManager.GetString("strStartLoggerOfGroupNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop External Logger.
        /// </summary>
        internal static string strStopExternalLogger {
            get {
                return ResourceManager.GetString("strStopExternalLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop External Logger Of Group No.
        /// </summary>
        internal static string strStopExternalLoggerOfGroupNo {
            get {
                return ResourceManager.GetString("strStopExternalLoggerOfGroupNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Logger.
        /// </summary>
        internal static string strStopLogger {
            get {
                return ResourceManager.GetString("strStopLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Logger Of Group No.
        /// </summary>
        internal static string strStopLoggerOfGroupNo {
            get {
                return ResourceManager.GetString("strStopLoggerOfGroupNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract a Constant Value from a Tag.
        /// </summary>
        internal static string strSubtractAConstantValueFromATag {
            get {
                return ResourceManager.GetString("strSubtractAConstantValueFromATag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract Tag B from Tag A.
        /// </summary>
        internal static string strSubtractTagBFromTagA {
            get {
                return ResourceManager.GetString("strSubtractTagBFromTagA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap Tag A and Tag B.
        /// </summary>
        internal static string strSwapTagAAndTagB {
            get {
                return ResourceManager.GetString("strSwapTagAAndTagB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Bit.
        /// </summary>
        internal static string strToggleBit {
            get {
                return ResourceManager.GetString("strToggleBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Bit OFF.
        /// </summary>
        internal static string strTurnBitOFF {
            get {
                return ResourceManager.GetString("strTurnBitOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Bit ON.
        /// </summary>
        internal static string strTurnBitON {
            get {
                return ResourceManager.GetString("strTurnBitON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string strUnm {
            get {
                return ResourceManager.GetString("strUnm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Log Upload.
        /// </summary>
        internal static string strUSBDataLogUpload {
            get {
                return ResourceManager.GetString("strUSBDataLogUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB Host Upload.
        /// </summary>
        internal static string strUSBHostUpload {
            get {
                return ResourceManager.GetString("strUSBHostUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait While.
        /// </summary>
        internal static string strWait {
            get {
                return ResourceManager.GetString("strWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Value to Tag.
        /// </summary>
        internal static string strWriteValueToTag {
            get {
                return ResourceManager.GetString("strWriteValueToTag", resourceCulture);
            }
        }
    }
}
